package com.sigdue.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "ARCHIVO".
 */
@Entity
public class Archivo {

    @Id
    private long id_archivo;
    private Long id_usuario;
    private String tipo;
    private String media_type;
    private String ruta;
    private String nombre;
    private String descripcion;
    private String estado;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Archivo() {
    }

    public Archivo(long id_archivo) {
        this.id_archivo = id_archivo;
    }

    @Generated
    public Archivo(long id_archivo, Long id_usuario, String tipo, String media_type, String ruta, String nombre, String descripcion, String estado) {
        this.id_archivo = id_archivo;
        this.id_usuario = id_usuario;
        this.tipo = tipo;
        this.media_type = media_type;
        this.ruta = ruta;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.estado = estado;
    }

    public long getId_archivo() {
        return id_archivo;
    }

    public void setId_archivo(long id_archivo) {
        this.id_archivo = id_archivo;
    }

    public Long getId_usuario() {
        return id_usuario;
    }

    public void setId_usuario(Long id_usuario) {
        this.id_usuario = id_usuario;
    }

    public String getTipo() {
        return tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    public String getMedia_type() {
        return media_type;
    }

    public void setMedia_type(String media_type) {
        this.media_type = media_type;
    }

    public String getRuta() {
        return ruta;
    }

    public void setRuta(String ruta) {
        this.ruta = ruta;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public String getEstado() {
        return estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
