package com.sigdue.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "ARCHIVO".
 */
@Entity
public class Archivo {

    @Id
    private long id_predial;
    private String ruta;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Archivo() {
    }

    public Archivo(long id_predial) {
        this.id_predial = id_predial;
    }

    @Generated
    public Archivo(long id_predial, String ruta) {
        this.id_predial = id_predial;
        this.ruta = ruta;
    }

    public long getId_predial() {
        return id_predial;
    }

    public void setId_predial(long id_predial) {
        this.id_predial = id_predial;
    }

    public String getRuta() {
        return ruta;
    }

    public void setRuta(String ruta) {
        this.ruta = ruta;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
