package com.sigdue.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "CLASE_VEHICULO".
 */
@Entity
public class ClaseVehiculo {

    @Id
    private long id_clase_vehiculo;
    private String nom_clase_vehiculo;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public ClaseVehiculo() {
    }

    public ClaseVehiculo(long id_clase_vehiculo) {
        this.id_clase_vehiculo = id_clase_vehiculo;
    }

    @Generated
    public ClaseVehiculo(long id_clase_vehiculo, String nom_clase_vehiculo) {
        this.id_clase_vehiculo = id_clase_vehiculo;
        this.nom_clase_vehiculo = nom_clase_vehiculo;
    }

    public long getId_clase_vehiculo() {
        return id_clase_vehiculo;
    }

    public void setId_clase_vehiculo(long id_clase_vehiculo) {
        this.id_clase_vehiculo = id_clase_vehiculo;
    }

    public String getNom_clase_vehiculo() {
        return nom_clase_vehiculo;
    }

    public void setNom_clase_vehiculo(String nom_clase_vehiculo) {
        this.nom_clase_vehiculo = nom_clase_vehiculo;
    }

    // KEEP METHODS - put your custom methods here
    public String toString() {
        return getId_clase_vehiculo() + ". " + getNom_clase_vehiculo();
    }
    // KEEP METHODS END

}
