package com.sigdue.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CLASE_VEHICULO".
*/
public class ClaseVehiculoDao extends AbstractDao<ClaseVehiculo, Long> {

    public static final String TABLENAME = "CLASE_VEHICULO";

    /**
     * Properties of entity ClaseVehiculo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id_clase_vehiculo = new Property(0, long.class, "id_clase_vehiculo", true, "ID_CLASE_VEHICULO");
        public final static Property Nom_clase_vehiculo = new Property(1, String.class, "nom_clase_vehiculo", false, "NOM_CLASE_VEHICULO");
    }


    public ClaseVehiculoDao(DaoConfig config) {
        super(config);
    }
    
    public ClaseVehiculoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CLASE_VEHICULO\" (" + //
                "\"ID_CLASE_VEHICULO\" INTEGER PRIMARY KEY NOT NULL ," + // 0: id_clase_vehiculo
                "\"NOM_CLASE_VEHICULO\" TEXT);"); // 1: nom_clase_vehiculo
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CLASE_VEHICULO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ClaseVehiculo entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId_clase_vehiculo());
 
        String nom_clase_vehiculo = entity.getNom_clase_vehiculo();
        if (nom_clase_vehiculo != null) {
            stmt.bindString(2, nom_clase_vehiculo);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ClaseVehiculo entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId_clase_vehiculo());
 
        String nom_clase_vehiculo = entity.getNom_clase_vehiculo();
        if (nom_clase_vehiculo != null) {
            stmt.bindString(2, nom_clase_vehiculo);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public ClaseVehiculo readEntity(Cursor cursor, int offset) {
        ClaseVehiculo entity = new ClaseVehiculo( //
            cursor.getLong(offset + 0), // id_clase_vehiculo
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // nom_clase_vehiculo
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ClaseVehiculo entity, int offset) {
        entity.setId_clase_vehiculo(cursor.getLong(offset + 0));
        entity.setNom_clase_vehiculo(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ClaseVehiculo entity, long rowId) {
        entity.setId_clase_vehiculo(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ClaseVehiculo entity) {
        if(entity != null) {
            return entity.getId_clase_vehiculo();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ClaseVehiculo entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
