package com.sigdue.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "COLOR".
 */
@Entity
public class Color {

    @Id
    private long id_color;
    private String nom_color;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Color() {
    }

    public Color(long id_color) {
        this.id_color = id_color;
    }

    @Generated
    public Color(long id_color, String nom_color) {
        this.id_color = id_color;
        this.nom_color = nom_color;
    }

    public long getId_color() {
        return id_color;
    }

    public void setId_color(long id_color) {
        this.id_color = id_color;
    }

    public String getNom_color() {
        return nom_color;
    }

    public void setNom_color(String nom_color) {
        this.nom_color = nom_color;
    }

    // KEEP METHODS - put your custom methods here
    public String toString() {
        return getId_color() + ". " + getNom_color();
    }
    // KEEP METHODS END

}
