package com.sigdue.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "COLOR".
*/
public class ColorDao extends AbstractDao<Color, Long> {

    public static final String TABLENAME = "COLOR";

    /**
     * Properties of entity Color.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id_color = new Property(0, long.class, "id_color", true, "ID_COLOR");
        public final static Property Nom_color = new Property(1, String.class, "nom_color", false, "NOM_COLOR");
    }


    public ColorDao(DaoConfig config) {
        super(config);
    }
    
    public ColorDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"COLOR\" (" + //
                "\"ID_COLOR\" INTEGER PRIMARY KEY NOT NULL ," + // 0: id_color
                "\"NOM_COLOR\" TEXT);"); // 1: nom_color
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"COLOR\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Color entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId_color());
 
        String nom_color = entity.getNom_color();
        if (nom_color != null) {
            stmt.bindString(2, nom_color);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Color entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId_color());
 
        String nom_color = entity.getNom_color();
        if (nom_color != null) {
            stmt.bindString(2, nom_color);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public Color readEntity(Cursor cursor, int offset) {
        Color entity = new Color( //
            cursor.getLong(offset + 0), // id_color
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // nom_color
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Color entity, int offset) {
        entity.setId_color(cursor.getLong(offset + 0));
        entity.setNom_color(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Color entity, long rowId) {
        entity.setId_color(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Color entity) {
        if(entity != null) {
            return entity.getId_color();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Color entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
