package com.sigdue.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.sigdue.db.Parametro;
import com.sigdue.db.Predial;
import com.sigdue.db.Archivo;
import com.sigdue.db.Usuario;

import com.sigdue.db.ParametroDao;
import com.sigdue.db.PredialDao;
import com.sigdue.db.ArchivoDao;
import com.sigdue.db.UsuarioDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig parametroDaoConfig;
    private final DaoConfig predialDaoConfig;
    private final DaoConfig archivoDaoConfig;
    private final DaoConfig usuarioDaoConfig;

    private final ParametroDao parametroDao;
    private final PredialDao predialDao;
    private final ArchivoDao archivoDao;
    private final UsuarioDao usuarioDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        parametroDaoConfig = daoConfigMap.get(ParametroDao.class).clone();
        parametroDaoConfig.initIdentityScope(type);

        predialDaoConfig = daoConfigMap.get(PredialDao.class).clone();
        predialDaoConfig.initIdentityScope(type);

        archivoDaoConfig = daoConfigMap.get(ArchivoDao.class).clone();
        archivoDaoConfig.initIdentityScope(type);

        usuarioDaoConfig = daoConfigMap.get(UsuarioDao.class).clone();
        usuarioDaoConfig.initIdentityScope(type);

        parametroDao = new ParametroDao(parametroDaoConfig, this);
        predialDao = new PredialDao(predialDaoConfig, this);
        archivoDao = new ArchivoDao(archivoDaoConfig, this);
        usuarioDao = new UsuarioDao(usuarioDaoConfig, this);

        registerDao(Parametro.class, parametroDao);
        registerDao(Predial.class, predialDao);
        registerDao(Archivo.class, archivoDao);
        registerDao(Usuario.class, usuarioDao);
    }
    
    public void clear() {
        parametroDaoConfig.clearIdentityScope();
        predialDaoConfig.clearIdentityScope();
        archivoDaoConfig.clearIdentityScope();
        usuarioDaoConfig.clearIdentityScope();
    }

    public ParametroDao getParametroDao() {
        return parametroDao;
    }

    public PredialDao getPredialDao() {
        return predialDao;
    }

    public ArchivoDao getArchivoDao() {
        return archivoDao;
    }

    public UsuarioDao getUsuarioDao() {
        return usuarioDao;
    }

}
