package com.sigdue.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "DEPARTAMENTO".
 */
@Entity
public class Departamento {

    @Id
    @NotNull
    private String id_departamento;
    private String nom_departamento;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Departamento() {
    }

    public Departamento(String id_departamento) {
        this.id_departamento = id_departamento;
    }

    @Generated
    public Departamento(String id_departamento, String nom_departamento) {
        this.id_departamento = id_departamento;
        this.nom_departamento = nom_departamento;
    }

    @NotNull
    public String getId_departamento() {
        return id_departamento;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setId_departamento(@NotNull String id_departamento) {
        this.id_departamento = id_departamento;
    }

    public String getNom_departamento() {
        return nom_departamento;
    }

    public void setNom_departamento(String nom_departamento) {
        this.nom_departamento = nom_departamento;
    }

    // KEEP METHODS - put your custom methods here
    public String toString() {
        return getId_departamento() + ". " + getNom_departamento();
    }
    // KEEP METHODS END

}
