package com.sigdue.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DEPARTAMENTO".
*/
public class DepartamentoDao extends AbstractDao<Departamento, String> {

    public static final String TABLENAME = "DEPARTAMENTO";

    /**
     * Properties of entity Departamento.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id_departamento = new Property(0, String.class, "id_departamento", true, "ID_DEPARTAMENTO");
        public final static Property Nom_departamento = new Property(1, String.class, "nom_departamento", false, "NOM_DEPARTAMENTO");
    }


    public DepartamentoDao(DaoConfig config) {
        super(config);
    }
    
    public DepartamentoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DEPARTAMENTO\" (" + //
                "\"ID_DEPARTAMENTO\" TEXT PRIMARY KEY NOT NULL ," + // 0: id_departamento
                "\"NOM_DEPARTAMENTO\" TEXT);"); // 1: nom_departamento
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DEPARTAMENTO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Departamento entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getId_departamento());
 
        String nom_departamento = entity.getNom_departamento();
        if (nom_departamento != null) {
            stmt.bindString(2, nom_departamento);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Departamento entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getId_departamento());
 
        String nom_departamento = entity.getNom_departamento();
        if (nom_departamento != null) {
            stmt.bindString(2, nom_departamento);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }    

    @Override
    public Departamento readEntity(Cursor cursor, int offset) {
        Departamento entity = new Departamento( //
            cursor.getString(offset + 0), // id_departamento
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // nom_departamento
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Departamento entity, int offset) {
        entity.setId_departamento(cursor.getString(offset + 0));
        entity.setNom_departamento(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final String updateKeyAfterInsert(Departamento entity, long rowId) {
        return entity.getId_departamento();
    }
    
    @Override
    public String getKey(Departamento entity) {
        if(entity != null) {
            return entity.getId_departamento();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Departamento entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
