package com.sigdue.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "GRUA".
 */
@Entity
public class Grua {

    @Id
    private long id_grua;

    @Unique
    private String placa;
    private String no_grua;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Grua() {
    }

    public Grua(long id_grua) {
        this.id_grua = id_grua;
    }

    @Generated
    public Grua(long id_grua, String placa, String no_grua) {
        this.id_grua = id_grua;
        this.placa = placa;
        this.no_grua = no_grua;
    }

    public long getId_grua() {
        return id_grua;
    }

    public void setId_grua(long id_grua) {
        this.id_grua = id_grua;
    }

    public String getPlaca() {
        return placa;
    }

    public void setPlaca(String placa) {
        this.placa = placa;
    }

    public String getNo_grua() {
        return no_grua;
    }

    public void setNo_grua(String no_grua) {
        this.no_grua = no_grua;
    }

    // KEEP METHODS - put your custom methods here
    public String toString() {
        return getNo_grua() + ". " + getPlaca() + " ";
    }
    // KEEP METHODS END

}
