package com.sigdue.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GRUA".
*/
public class GruaDao extends AbstractDao<Grua, Long> {

    public static final String TABLENAME = "GRUA";

    /**
     * Properties of entity Grua.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id_grua = new Property(0, long.class, "id_grua", true, "ID_GRUA");
        public final static Property Placa = new Property(1, String.class, "placa", false, "PLACA");
        public final static Property No_grua = new Property(2, String.class, "no_grua", false, "NO_GRUA");
    }


    public GruaDao(DaoConfig config) {
        super(config);
    }
    
    public GruaDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GRUA\" (" + //
                "\"ID_GRUA\" INTEGER PRIMARY KEY NOT NULL ," + // 0: id_grua
                "\"PLACA\" TEXT UNIQUE ," + // 1: placa
                "\"NO_GRUA\" TEXT);"); // 2: no_grua
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GRUA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Grua entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId_grua());
 
        String placa = entity.getPlaca();
        if (placa != null) {
            stmt.bindString(2, placa);
        }
 
        String no_grua = entity.getNo_grua();
        if (no_grua != null) {
            stmt.bindString(3, no_grua);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Grua entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId_grua());
 
        String placa = entity.getPlaca();
        if (placa != null) {
            stmt.bindString(2, placa);
        }
 
        String no_grua = entity.getNo_grua();
        if (no_grua != null) {
            stmt.bindString(3, no_grua);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public Grua readEntity(Cursor cursor, int offset) {
        Grua entity = new Grua( //
            cursor.getLong(offset + 0), // id_grua
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // placa
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // no_grua
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Grua entity, int offset) {
        entity.setId_grua(cursor.getLong(offset + 0));
        entity.setPlaca(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setNo_grua(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Grua entity, long rowId) {
        entity.setId_grua(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Grua entity) {
        if(entity != null) {
            return entity.getId_grua();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Grua entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
