package com.sigdue.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "INFRACCION".
 */
@Entity
public class Infraccion {

    @Id
    private long id_infraccion;

    @Unique
    private String codigo;
    private String descripcion;
    private String inmovilizacion;
    private Long R1;
    private Long R2;
    private Long R3;
    private Long R4;
    private Long R5;
    private Long R6;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Infraccion() {
    }

    public Infraccion(long id_infraccion) {
        this.id_infraccion = id_infraccion;
    }

    @Generated
    public Infraccion(long id_infraccion, String codigo, String descripcion, String inmovilizacion, Long R1, Long R2, Long R3, Long R4, Long R5, Long R6) {
        this.id_infraccion = id_infraccion;
        this.codigo = codigo;
        this.descripcion = descripcion;
        this.inmovilizacion = inmovilizacion;
        this.R1 = R1;
        this.R2 = R2;
        this.R3 = R3;
        this.R4 = R4;
        this.R5 = R5;
        this.R6 = R6;
    }

    public long getId_infraccion() {
        return id_infraccion;
    }

    public void setId_infraccion(long id_infraccion) {
        this.id_infraccion = id_infraccion;
    }

    public String getCodigo() {
        return codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public String getInmovilizacion() {
        return inmovilizacion;
    }

    public void setInmovilizacion(String inmovilizacion) {
        this.inmovilizacion = inmovilizacion;
    }

    public Long getR1() {
        return R1;
    }

    public void setR1(Long R1) {
        this.R1 = R1;
    }

    public Long getR2() {
        return R2;
    }

    public void setR2(Long R2) {
        this.R2 = R2;
    }

    public Long getR3() {
        return R3;
    }

    public void setR3(Long R3) {
        this.R3 = R3;
    }

    public Long getR4() {
        return R4;
    }

    public void setR4(Long R4) {
        this.R4 = R4;
    }

    public Long getR5() {
        return R5;
    }

    public void setR5(Long R5) {
        this.R5 = R5;
    }

    public Long getR6() {
        return R6;
    }

    public void setR6(Long R6) {
        this.R6 = R6;
    }

    // KEEP METHODS - put your custom methods here
    public String toString() {
        return getCodigo() + ". " + getDescripcion().toLowerCase() + " ";
    }
    // KEEP METHODS END

}
