package com.sigdue.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "PARAMETRO".
 */
@Entity
public class Parametro {

    @Id(autoincrement = true)
    private long id_parametro;
    private String tipo;
    private String valor;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Parametro() {
    }

    public Parametro(long id_parametro) {
        this.id_parametro = id_parametro;
    }

    @Generated
    public Parametro(long id_parametro, String tipo, String valor) {
        this.id_parametro = id_parametro;
        this.tipo = tipo;
        this.valor = valor;
    }

    public long getId_parametro() {
        return id_parametro;
    }

    public void setId_parametro(long id_parametro) {
        this.id_parametro = id_parametro;
    }

    public String getTipo() {
        return tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    public String getValor() {
        return valor;
    }

    public void setValor(String valor) {
        this.valor = valor;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
