package com.sigdue.db;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PARQUEADERO".
*/
public class ParqueaderoDao extends AbstractDao<Parqueadero, Long> {

    public static final String TABLENAME = "PARQUEADERO";

    /**
     * Properties of entity Parqueadero.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id_parqueadero = new Property(0, long.class, "id_parqueadero", true, "ID_PARQUEADERO");
        public final static Property Nombre = new Property(1, String.class, "nombre", false, "NOMBRE");
        public final static Property Direccion = new Property(2, String.class, "direccion", false, "DIRECCION");
        public final static Property Telefono = new Property(3, String.class, "telefono", false, "TELEFONO");
        public final static Property Id_municipio = new Property(4, String.class, "id_municipio", false, "ID_MUNICIPIO");
    }

    private DaoSession daoSession;


    public ParqueaderoDao(DaoConfig config) {
        super(config);
    }
    
    public ParqueaderoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PARQUEADERO\" (" + //
                "\"ID_PARQUEADERO\" INTEGER PRIMARY KEY NOT NULL ," + // 0: id_parqueadero
                "\"NOMBRE\" TEXT," + // 1: nombre
                "\"DIRECCION\" TEXT," + // 2: direccion
                "\"TELEFONO\" TEXT," + // 3: telefono
                "\"ID_MUNICIPIO\" TEXT);"); // 4: id_municipio
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PARQUEADERO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Parqueadero entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId_parqueadero());
 
        String nombre = entity.getNombre();
        if (nombre != null) {
            stmt.bindString(2, nombre);
        }
 
        String direccion = entity.getDireccion();
        if (direccion != null) {
            stmt.bindString(3, direccion);
        }
 
        String telefono = entity.getTelefono();
        if (telefono != null) {
            stmt.bindString(4, telefono);
        }
 
        String id_municipio = entity.getId_municipio();
        if (id_municipio != null) {
            stmt.bindString(5, id_municipio);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Parqueadero entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId_parqueadero());
 
        String nombre = entity.getNombre();
        if (nombre != null) {
            stmt.bindString(2, nombre);
        }
 
        String direccion = entity.getDireccion();
        if (direccion != null) {
            stmt.bindString(3, direccion);
        }
 
        String telefono = entity.getTelefono();
        if (telefono != null) {
            stmt.bindString(4, telefono);
        }
 
        String id_municipio = entity.getId_municipio();
        if (id_municipio != null) {
            stmt.bindString(5, id_municipio);
        }
    }

    @Override
    protected final void attachEntity(Parqueadero entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public Parqueadero readEntity(Cursor cursor, int offset) {
        Parqueadero entity = new Parqueadero( //
            cursor.getLong(offset + 0), // id_parqueadero
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // nombre
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // direccion
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // telefono
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // id_municipio
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Parqueadero entity, int offset) {
        entity.setId_parqueadero(cursor.getLong(offset + 0));
        entity.setNombre(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDireccion(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTelefono(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setId_municipio(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Parqueadero entity, long rowId) {
        entity.setId_parqueadero(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Parqueadero entity) {
        if(entity != null) {
            return entity.getId_parqueadero();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Parqueadero entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getMunicipioDao().getAllColumns());
            builder.append(" FROM PARQUEADERO T");
            builder.append(" LEFT JOIN MUNICIPIO T0 ON T.\"ID_MUNICIPIO\"=T0.\"ID_MUNICIPIO\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Parqueadero loadCurrentDeep(Cursor cursor, boolean lock) {
        Parqueadero entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Municipio municipio = loadCurrentOther(daoSession.getMunicipioDao(), cursor, offset);
        entity.setMunicipio(municipio);

        return entity;    
    }

    public Parqueadero loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Parqueadero> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Parqueadero> list = new ArrayList<Parqueadero>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Parqueadero> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Parqueadero> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
