package com.sigdue.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "PREDIAL".
 */
@Entity
public class Predial {

    @Id
    private long id_predial;
    private String dane_sede;
    private String cod_predio;
    private String clima;
    private String distancia_mts_sede_ppal;
    private String dist_km_centro_poblado;
    private String clase_predio;
    private String avaluo_catastral;
    private String fec_avaluo_catastral;
    private String avaluo_comercial;
    private String fec_avaluo_comercial;
    private String zona_aislamiento;
    private String zona_alto_riesgo;
    private String zona_proteccion;
    private String topografia;
    private String propiedad_lote;
    private String tipo_documento;
    private String cual_tipo_documento;
    private String nro_documento_legalizacion;
    private String fec_expedicion;
    private String notaria_dependencia_origen;
    private String lugar_expedicion;
    private String registro_catastral;
    private String matricula_inmobiliaria;
    private String propietarios;
    private String tenencia;
    private String con_quien_tenencia;
    private String nom_quien_tenencia;
    private String fecha_tenencia_lote;
    private String estado;
    private String id_bd;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Predial() {
    }

    public Predial(long id_predial) {
        this.id_predial = id_predial;
    }

    @Generated
    public Predial(long id_predial, String dane_sede, String cod_predio, String clima, String distancia_mts_sede_ppal, String dist_km_centro_poblado, String clase_predio, String avaluo_catastral, String fec_avaluo_catastral, String avaluo_comercial, String fec_avaluo_comercial, String zona_aislamiento, String zona_alto_riesgo, String zona_proteccion, String topografia, String propiedad_lote, String tipo_documento, String cual_tipo_documento, String nro_documento_legalizacion, String fec_expedicion, String notaria_dependencia_origen, String lugar_expedicion, String registro_catastral, String matricula_inmobiliaria, String propietarios, String tenencia, String con_quien_tenencia, String nom_quien_tenencia, String fecha_tenencia_lote, String estado, String id_bd) {
        this.id_predial = id_predial;
        this.dane_sede = dane_sede;
        this.cod_predio = cod_predio;
        this.clima = clima;
        this.distancia_mts_sede_ppal = distancia_mts_sede_ppal;
        this.dist_km_centro_poblado = dist_km_centro_poblado;
        this.clase_predio = clase_predio;
        this.avaluo_catastral = avaluo_catastral;
        this.fec_avaluo_catastral = fec_avaluo_catastral;
        this.avaluo_comercial = avaluo_comercial;
        this.fec_avaluo_comercial = fec_avaluo_comercial;
        this.zona_aislamiento = zona_aislamiento;
        this.zona_alto_riesgo = zona_alto_riesgo;
        this.zona_proteccion = zona_proteccion;
        this.topografia = topografia;
        this.propiedad_lote = propiedad_lote;
        this.tipo_documento = tipo_documento;
        this.cual_tipo_documento = cual_tipo_documento;
        this.nro_documento_legalizacion = nro_documento_legalizacion;
        this.fec_expedicion = fec_expedicion;
        this.notaria_dependencia_origen = notaria_dependencia_origen;
        this.lugar_expedicion = lugar_expedicion;
        this.registro_catastral = registro_catastral;
        this.matricula_inmobiliaria = matricula_inmobiliaria;
        this.propietarios = propietarios;
        this.tenencia = tenencia;
        this.con_quien_tenencia = con_quien_tenencia;
        this.nom_quien_tenencia = nom_quien_tenencia;
        this.fecha_tenencia_lote = fecha_tenencia_lote;
        this.estado = estado;
        this.id_bd = id_bd;
    }

    public long getId_predial() {
        return id_predial;
    }

    public void setId_predial(long id_predial) {
        this.id_predial = id_predial;
    }

    public String getDane_sede() {
        return dane_sede;
    }

    public void setDane_sede(String dane_sede) {
        this.dane_sede = dane_sede;
    }

    public String getCod_predio() {
        return cod_predio;
    }

    public void setCod_predio(String cod_predio) {
        this.cod_predio = cod_predio;
    }

    public String getClima() {
        return clima;
    }

    public void setClima(String clima) {
        this.clima = clima;
    }

    public String getDistancia_mts_sede_ppal() {
        return distancia_mts_sede_ppal;
    }

    public void setDistancia_mts_sede_ppal(String distancia_mts_sede_ppal) {
        this.distancia_mts_sede_ppal = distancia_mts_sede_ppal;
    }

    public String getDist_km_centro_poblado() {
        return dist_km_centro_poblado;
    }

    public void setDist_km_centro_poblado(String dist_km_centro_poblado) {
        this.dist_km_centro_poblado = dist_km_centro_poblado;
    }

    public String getClase_predio() {
        return clase_predio;
    }

    public void setClase_predio(String clase_predio) {
        this.clase_predio = clase_predio;
    }

    public String getAvaluo_catastral() {
        return avaluo_catastral;
    }

    public void setAvaluo_catastral(String avaluo_catastral) {
        this.avaluo_catastral = avaluo_catastral;
    }

    public String getFec_avaluo_catastral() {
        return fec_avaluo_catastral;
    }

    public void setFec_avaluo_catastral(String fec_avaluo_catastral) {
        this.fec_avaluo_catastral = fec_avaluo_catastral;
    }

    public String getAvaluo_comercial() {
        return avaluo_comercial;
    }

    public void setAvaluo_comercial(String avaluo_comercial) {
        this.avaluo_comercial = avaluo_comercial;
    }

    public String getFec_avaluo_comercial() {
        return fec_avaluo_comercial;
    }

    public void setFec_avaluo_comercial(String fec_avaluo_comercial) {
        this.fec_avaluo_comercial = fec_avaluo_comercial;
    }

    public String getZona_aislamiento() {
        return zona_aislamiento;
    }

    public void setZona_aislamiento(String zona_aislamiento) {
        this.zona_aislamiento = zona_aislamiento;
    }

    public String getZona_alto_riesgo() {
        return zona_alto_riesgo;
    }

    public void setZona_alto_riesgo(String zona_alto_riesgo) {
        this.zona_alto_riesgo = zona_alto_riesgo;
    }

    public String getZona_proteccion() {
        return zona_proteccion;
    }

    public void setZona_proteccion(String zona_proteccion) {
        this.zona_proteccion = zona_proteccion;
    }

    public String getTopografia() {
        return topografia;
    }

    public void setTopografia(String topografia) {
        this.topografia = topografia;
    }

    public String getPropiedad_lote() {
        return propiedad_lote;
    }

    public void setPropiedad_lote(String propiedad_lote) {
        this.propiedad_lote = propiedad_lote;
    }

    public String getTipo_documento() {
        return tipo_documento;
    }

    public void setTipo_documento(String tipo_documento) {
        this.tipo_documento = tipo_documento;
    }

    public String getCual_tipo_documento() {
        return cual_tipo_documento;
    }

    public void setCual_tipo_documento(String cual_tipo_documento) {
        this.cual_tipo_documento = cual_tipo_documento;
    }

    public String getNro_documento_legalizacion() {
        return nro_documento_legalizacion;
    }

    public void setNro_documento_legalizacion(String nro_documento_legalizacion) {
        this.nro_documento_legalizacion = nro_documento_legalizacion;
    }

    public String getFec_expedicion() {
        return fec_expedicion;
    }

    public void setFec_expedicion(String fec_expedicion) {
        this.fec_expedicion = fec_expedicion;
    }

    public String getNotaria_dependencia_origen() {
        return notaria_dependencia_origen;
    }

    public void setNotaria_dependencia_origen(String notaria_dependencia_origen) {
        this.notaria_dependencia_origen = notaria_dependencia_origen;
    }

    public String getLugar_expedicion() {
        return lugar_expedicion;
    }

    public void setLugar_expedicion(String lugar_expedicion) {
        this.lugar_expedicion = lugar_expedicion;
    }

    public String getRegistro_catastral() {
        return registro_catastral;
    }

    public void setRegistro_catastral(String registro_catastral) {
        this.registro_catastral = registro_catastral;
    }

    public String getMatricula_inmobiliaria() {
        return matricula_inmobiliaria;
    }

    public void setMatricula_inmobiliaria(String matricula_inmobiliaria) {
        this.matricula_inmobiliaria = matricula_inmobiliaria;
    }

    public String getPropietarios() {
        return propietarios;
    }

    public void setPropietarios(String propietarios) {
        this.propietarios = propietarios;
    }

    public String getTenencia() {
        return tenencia;
    }

    public void setTenencia(String tenencia) {
        this.tenencia = tenencia;
    }

    public String getCon_quien_tenencia() {
        return con_quien_tenencia;
    }

    public void setCon_quien_tenencia(String con_quien_tenencia) {
        this.con_quien_tenencia = con_quien_tenencia;
    }

    public String getNom_quien_tenencia() {
        return nom_quien_tenencia;
    }

    public void setNom_quien_tenencia(String nom_quien_tenencia) {
        this.nom_quien_tenencia = nom_quien_tenencia;
    }

    public String getFecha_tenencia_lote() {
        return fecha_tenencia_lote;
    }

    public void setFecha_tenencia_lote(String fecha_tenencia_lote) {
        this.fecha_tenencia_lote = fecha_tenencia_lote;
    }

    public String getEstado() {
        return estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    public String getId_bd() {
        return id_bd;
    }

    public void setId_bd(String id_bd) {
        this.id_bd = id_bd;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
