package com.sigdue.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "TIPO_IDENTIFICACION".
 */
@Entity
public class TipoIdentificacion {

    @Id
    @NotNull
    private String id_tipo_identificacion;
    private String nombre;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public TipoIdentificacion() {
    }

    public TipoIdentificacion(String id_tipo_identificacion) {
        this.id_tipo_identificacion = id_tipo_identificacion;
    }

    @Generated
    public TipoIdentificacion(String id_tipo_identificacion, String nombre) {
        this.id_tipo_identificacion = id_tipo_identificacion;
        this.nombre = nombre;
    }

    @NotNull
    public String getId_tipo_identificacion() {
        return id_tipo_identificacion;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setId_tipo_identificacion(@NotNull String id_tipo_identificacion) {
        this.id_tipo_identificacion = id_tipo_identificacion;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    // KEEP METHODS - put your custom methods here
    public String toString() {
        return getId_tipo_identificacion() + ". " + getNombre();
    }
    // KEEP METHODS END

}
