package com.sigdue.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USUARIO".
*/
public class UsuarioDao extends AbstractDao<Usuario, Long> {

    public static final String TABLENAME = "USUARIO";

    /**
     * Properties of entity Usuario.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id_usuario = new Property(0, long.class, "id_usuario", true, "ID_USUARIO");
        public final static Property Usuario = new Property(1, String.class, "usuario", false, "USUARIO");
        public final static Property Contrasena = new Property(2, String.class, "contrasena", false, "CONTRASENA");
    }


    public UsuarioDao(DaoConfig config) {
        super(config);
    }
    
    public UsuarioDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USUARIO\" (" + //
                "\"ID_USUARIO\" INTEGER PRIMARY KEY NOT NULL ," + // 0: id_usuario
                "\"USUARIO\" TEXT UNIQUE ," + // 1: usuario
                "\"CONTRASENA\" TEXT);"); // 2: contrasena
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USUARIO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Usuario entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId_usuario());
 
        String usuario = entity.getUsuario();
        if (usuario != null) {
            stmt.bindString(2, usuario);
        }
 
        String contrasena = entity.getContrasena();
        if (contrasena != null) {
            stmt.bindString(3, contrasena);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Usuario entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId_usuario());
 
        String usuario = entity.getUsuario();
        if (usuario != null) {
            stmt.bindString(2, usuario);
        }
 
        String contrasena = entity.getContrasena();
        if (contrasena != null) {
            stmt.bindString(3, contrasena);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public Usuario readEntity(Cursor cursor, int offset) {
        Usuario entity = new Usuario( //
            cursor.getLong(offset + 0), // id_usuario
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // usuario
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // contrasena
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Usuario entity, int offset) {
        entity.setId_usuario(cursor.getLong(offset + 0));
        entity.setUsuario(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setContrasena(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Usuario entity, long rowId) {
        entity.setId_usuario(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Usuario entity) {
        if(entity != null) {
            return entity.getId_usuario();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Usuario entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
