package com.sigdue.db;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ZONAS".
*/
public class ZonasDao extends AbstractDao<Zonas, Long> {

    public static final String TABLENAME = "ZONAS";

    /**
     * Properties of entity Zonas.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id_zona = new Property(0, long.class, "id_zona", true, "ID_ZONA");
        public final static Property Nom_zona = new Property(1, String.class, "nom_zona", false, "NOM_ZONA");
        public final static Property Descripcion = new Property(2, String.class, "descripcion", false, "DESCRIPCION");
        public final static Property Id_municipio = new Property(3, String.class, "id_municipio", false, "ID_MUNICIPIO");
    }

    private DaoSession daoSession;


    public ZonasDao(DaoConfig config) {
        super(config);
    }
    
    public ZonasDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ZONAS\" (" + //
                "\"ID_ZONA\" INTEGER PRIMARY KEY NOT NULL ," + // 0: id_zona
                "\"NOM_ZONA\" TEXT," + // 1: nom_zona
                "\"DESCRIPCION\" TEXT," + // 2: descripcion
                "\"ID_MUNICIPIO\" TEXT);"); // 3: id_municipio
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ZONAS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Zonas entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId_zona());
 
        String nom_zona = entity.getNom_zona();
        if (nom_zona != null) {
            stmt.bindString(2, nom_zona);
        }
 
        String descripcion = entity.getDescripcion();
        if (descripcion != null) {
            stmt.bindString(3, descripcion);
        }
 
        String id_municipio = entity.getId_municipio();
        if (id_municipio != null) {
            stmt.bindString(4, id_municipio);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Zonas entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId_zona());
 
        String nom_zona = entity.getNom_zona();
        if (nom_zona != null) {
            stmt.bindString(2, nom_zona);
        }
 
        String descripcion = entity.getDescripcion();
        if (descripcion != null) {
            stmt.bindString(3, descripcion);
        }
 
        String id_municipio = entity.getId_municipio();
        if (id_municipio != null) {
            stmt.bindString(4, id_municipio);
        }
    }

    @Override
    protected final void attachEntity(Zonas entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public Zonas readEntity(Cursor cursor, int offset) {
        Zonas entity = new Zonas( //
            cursor.getLong(offset + 0), // id_zona
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // nom_zona
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // descripcion
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // id_municipio
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Zonas entity, int offset) {
        entity.setId_zona(cursor.getLong(offset + 0));
        entity.setNom_zona(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDescripcion(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setId_municipio(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Zonas entity, long rowId) {
        entity.setId_zona(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Zonas entity) {
        if(entity != null) {
            return entity.getId_zona();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Zonas entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getMunicipioDao().getAllColumns());
            builder.append(" FROM ZONAS T");
            builder.append(" LEFT JOIN MUNICIPIO T0 ON T.\"ID_MUNICIPIO\"=T0.\"ID_MUNICIPIO\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Zonas loadCurrentDeep(Cursor cursor, boolean lock) {
        Zonas entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Municipio municipio = loadCurrentOther(daoSession.getMunicipioDao(), cursor, offset);
        entity.setMunicipio(municipio);

        return entity;    
    }

    public Zonas loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Zonas> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Zonas> list = new ArrayList<Zonas>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Zonas> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Zonas> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
